//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.26 at 09:44:04 PM MSK 
//


package ktelabs.edu.hospitalmanagement.jaxb.soapEntities;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="doctorId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="numberOfAppointments" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="durationOfAppointments" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="hourOfStart" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "doctorId",
    "numberOfAppointments",
    "date",
    "durationOfAppointments",
    "hourOfStart"
})
@XmlRootElement(name = "addTicketsRequest")
public class AddTicketsRequest {

    protected long doctorId;
    protected int numberOfAppointments;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    protected int durationOfAppointments;
    protected int hourOfStart;

    /**
     * Gets the value of the doctorId property.
     * 
     */
    public long getDoctorId() {
        return doctorId;
    }

    /**
     * Sets the value of the doctorId property.
     * 
     */
    public void setDoctorId(long value) {
        this.doctorId = value;
    }

    /**
     * Gets the value of the numberOfAppointments property.
     * 
     */
    public int getNumberOfAppointments() {
        return numberOfAppointments;
    }

    /**
     * Sets the value of the numberOfAppointments property.
     * 
     */
    public void setNumberOfAppointments(int value) {
        this.numberOfAppointments = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the durationOfAppointments property.
     * 
     */
    public int getDurationOfAppointments() {
        return durationOfAppointments;
    }

    /**
     * Sets the value of the durationOfAppointments property.
     * 
     */
    public void setDurationOfAppointments(int value) {
        this.durationOfAppointments = value;
    }

    /**
     * Gets the value of the hourOfStart property.
     * 
     */
    public int getHourOfStart() {
        return hourOfStart;
    }

    /**
     * Sets the value of the hourOfStart property.
     * 
     */
    public void setHourOfStart(int value) {
        this.hourOfStart = value;
    }

}
