//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.26 at 09:44:04 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/SoapService/addTicket", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ktelabs.edu.hospitalmanagement.jaxb.soapEntities;
